### ISSUE TITLE
specializations

### ISSUE THREAD

**Issue by bukash** [leanleon93/bnsSkillRebinderPublic#6]
after the last update of the site, The images of specializations of classes disappeared, please tell me, can I get an archive with these images?

**Comment by bukash** [comment]
![Без названия](https://user-images.githubusercontent.com/68461889/87849090-79d51200-c8ee-11ea-9830-659b388655f0.png)
![Без названия (1)](https://user-images.githubusercontent.com/68461889/87849092-7d689900-c8ee-11ea-9b98-273b9e1cef4b.png)
![Без названия (2)](https://user-images.githubusercontent.com/68461889/87849093-7f325c80-c8ee-11ea-9cb6-2d44dfff051d.png)

**Comment by bukash** [comment]
and others

**Comment by leanleon93** [comment]
[icons.zip](https://github.com/leanleon93/bnsSkillRebinderPublic/files/4941453/icons.zip)
Sure no problem

**Comment by bukash** [comment]
ty
